### ISSUE TITLE
Datasets of UCM and Sydney with google drive instead of Baidu

### ISSUE THREAD

**Issue by RitaRamo** [201528014227051/RSICD_optimal#3]
Could you provide the datasets of UCM and Sydney with google drive?  Right now to download the datasets, it is required: “The content you download contains folder, please use the Baidu network disk client to download”.

**Comment by RitaRamo** [comment]
If that is not possible, you could sent me by e-mail: rita.mparada.ramos@gmail.com? Thank you in advance!

**Comment by 201528014227051** [comment]
can you try to download a baidu network disk client? @RitaRamo

**Comment by 201528014227051** [comment]
Rita Parada Ramos,
Thank you for attention.
Tips to get dataset by email:
You need to provide the purpose of using the database and make a promise not to be commercial. At the same time, you need to submit an email application database to my tutor, so that I have the right to email the database to you. You can find my tutor's email address on the front page of the paper




Binqiang Wang




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rita Parada Ramos"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月6日(星期六) 凌晨0:31
收件人:&nbsp;"201528014227051/RSICD_optimal"<RSICD_optimal@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [201528014227051/RSICD_optimal] Datasets of UCM and Sydney with google drive instead of Baidu (#3)





 
If that is not possible, you could sent me by e-mail: rita.mparada.ramos@gmail.com? Thank you in advance!

**Comment by RitaRamo** [comment]
Thank you for the prompt reply! I cannot downlaod the baidu network disk client, that is why I was wondering if you could provide them with the drive, as you did with RSICD dataset.  I am a PhD student at the University of Lisbon, I would like to use the datasets for writing a paper of remote sensing image captioning (I have no commercial purpose). Thank you again
